name: Remove Label on New Commit

on:
  pull_request:
    types: [synchronize]

jobs:
  remove-label:
    if: github.event.label.name == 'iso_ok'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Remove iso_ok label from PR
        uses: actions/github-script@v7
        with:
          script: |
            const { GITHUB_REF, GITHUB_TOKEN } = process.env;
            const prNumber = GITHUB_REF.split('/')[2]; 
            const labelToRemove = 'iso_ok';

            await github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              name: labelToRemove,
              headers: {
                authorization: `token ${GITHUB_TOKEN}`,
              },
            });
